# DATA_PATH = "data/pems_bay/pems_bay.csv"
# DATA_ADJ_PATH = "data/pems_bay/adj_pems_bay.csv"
# DATA_FEATURES = 325

DATA_PATH = "data/ca_2021_15min_resample/ca_his_2021.h5"
DATA_ADJ_PATH = "data/ca_2021_15min_resample/ca_rn_adj.npy"
DATA_FEATURES = 8600

DATA_STRIDE = 16
DATA_INPUT_LENGTH = 256
DATA_OUTPUT_LENGTH = 256
DATA_BATCH_SIZE = 32
DATA_NUM_WORKERS = 1
DATA_TRAIN_VAL_TEST_SPLIT = (0.6, 0.2, 0.2)
DATA_NORMALIZATION = "zscore"

MODEL_D_MODEL = 128
MODEL_NHEAD = 4
MODEL_DROPOUT = 0.
MODEL_NUM_LAYERS = 1
MODEL_ACTIVATION = "gelu"
MODEL_PATCH_SIZE = 16
MODEL_PATCH_STRIDE = 16

TRAINER_MAX_EPOCHS = 500
TRAINER_LR = 1e-4
TRAINER_WEIGHT_DECAY = 0
TRAINER_EARLY_STOPPING_PATIENCE = 50
TRAINER_GRADIENT_CLIP_ALGORITHM = "norm"
TRAINER_GRADIENT_CLIP_VAL = 1.0
TRAINER_PRECISION = "16-mixed"
