DATA_PATH = "data/pems_bay/pems_bay.csv"
DATA_ADJ_PATH = "data/pems_bay/adj_pems_bay.csv"
DATA_STRIDE = 16
DATA_INPUT_LENGTH = 256
DATA_OUTPUT_LENGTH = 256
DATA_FEATURES = 325
DATA_BATCH_SIZE = 64
DATA_NUM_WORKERS = 3
DATA_TRAIN_VAL_TEST_SPLIT = (0.6, 0.2, 0.2)
DATA_NORMALIZATION = "zscore"

MODEL_D_MODEL = 128
MODEL_NHEAD = 4
MODEL_DROPOUT = 0.0
MODEL_NUM_LAYERS = 2
MODEL_ACTIVATION = "gelu"
MODEL_PATCH_SIZE = 16
MODEL_PATCH_STRIDE = 16

TRAINER_MAX_EPOCHS = 500
TRAINER_LR = 1e-4
TRAINER_WEIGHT_DECAY = 0
TRAINER_EARLY_STOPPING_PATIENCE = 50
TRAINER_GRADIENT_CLIP_ALGORITHM = "norm"
TRAINER_GRADIENT_CLIP_VAL = 1.0
