from .anomaly_detection_framework import AnomalyDetectionFramework
from .autoencoding_framework import AutoEncodingFramework
from .classification_framework import ClassificationFramework
from .forecasting_framework import ForecastingFramework
from .regression_framework import RegressionFramework
